<div class="container">
<footer class="mastfoot mt-auto">
    <div class="inner">
        <p>Andreas Andersen, Hassanain Ali</p>
    </div>
</footer>
</div>

    <!-- Optional JavaScript -->
    <script>
        function change(val)
        {
            document.getElementById("target").value=val;
        }
    </script>
</div>
  </body>
</html>

<!--
<footer class="page-footer">
    <div class="container-fluid text-center">
        <h3>Datamatiker 2. semester hold E</h3>
        <p>Andreas Andersen og Hassanain Ali<br />Marts 2020</p>
    </div>
</footer>